name: Send Discord Build Notification
description: Send a notification to a Discord WebHook reflecting the success, failure, or cancellation of a GitHub Action.
author: Aneurin Barker Snook

branding:
  icon: check-circle
  color: green

inputs:
  color-failure:
    default: 11674146
    type: string

  color-success:
    default: 2273826
    type: string

  repository:
    required: true
    type: string

  result:
    required: true
    type: string

  run-id:
    required: true
    type: string

  run-number:
    required: true
    type: string

  webhook-url:
    required: true
    type: string

  workflow:
    required: true
    type: string

runs:
  using: node20
  main: dist/index.js
